import { Domain, Difficulty, QuestionType, Question, TosaLevel } from './types';

export const QUESTIONS: Question[] = [
  // --- INITIAL / BASIQUE (Environnement) ---
  {
    id: 1,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Dans quel onglet du ruban se trouve la fonction 'Figer les volets' ?",
    options: ["Accueil", "Insertion", "Mise en page", "Affichage"],
    correctAnswer: 3,
    explanation: "L'onglet 'Affichage' regroupe les options de visualisation. Figer les volets permet de garder les titres visibles.",
    trap: "Chercher dans 'Mise en page' (réservé à l'impression).",
    tip: "Visualisation = Affichage.",
  },
  {
    id: 2,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quel bouton permet de copier uniquement la mise en forme d'une cellule ?",
    options: ["Copier", "Pinceau (Reproduire la mise en forme)", "Coller", "Remplissage"],
    correctAnswer: 1,
    explanation: "L'icône du pinceau copie la couleur, la police et les bordures sans copier le texte.",
    trap: "Le bouton 'Copier' standard prend tout le contenu.",
    tip: "Un clic simple pour une fois, double-clic pour plusieurs fois.",
  },

  // --- INITIAL / BASIQUE (Calculs) ---
  {
    id: 3,
    domain: Domain.Calculs,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quelle formule est correcte pour faire la somme des cellules A1 et A2 ?",
    options: ["=A1+A2", "=SOMME(A1:A2)", "A1+A2", "Les deux premières sont correctes"],
    correctAnswer: 3,
    explanation: "Toute formule doit commencer par '='. On peut utiliser '+' ou la fonction SOMME.",
    trap: "Oublier le signe égal (=).",
    tip: "Pas d'égal, pas de calcul !",
  },
  {
    id: 4,
    domain: Domain.Calculs,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Écrivez la fonction pour trouver la valeur la plus basse dans la plage B2:B20.",
    correctAnswer: "=MIN(B2:B20)",
    explanation: "La fonction MIN renvoie le minimum d'une série de valeurs.",
    trap: "Confondre avec 'PETIT.VALEUR' qui demande plus de paramètres.",
    tip: "MIN pour minimum, MAX pour maximum.",
  },

  // --- INITIAL / BASIQUE (Mise en forme) ---
  {
    id: 5,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quel format appliquer pour afficher '0,25' sous la forme '25%' ?",
    options: ["Format Texte", "Format Nombre", "Format Pourcentage", "Format Comptabilité"],
    correctAnswer: 2,
    explanation: "Le format pourcentage multiplie visuellement la valeur par 100 et ajoute le symbole %.",
    trap: "Taper '%' manuellement transforme le chiffre en texte.",
    tip: "Utilisez le bouton '%' dans l'onglet Accueil.",
  },

  // --- OPÉRATIONNEL (Calculs) ---
  {
    id: 6,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "A1=100. Écrivez la formule pour calculer une remise de 15% sur ce montant.",
    correctAnswer: "=A1*0,15",
    explanation: "Multiplier par 0,15 donne le montant de la remise (15/100).",
    trap: "Multiplier par 1,15 (ce qui ajouterait 15% au lieu de calculer la remise).",
    tip: "X% = multiplier par X/100.",
  },
  {
    id: 7,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Que signifie l'erreur #DIV/0! ?",
    options: ["La cellule est trop petite", "La formule contient du texte", "Division par zéro", "Référence de cellule introuvable"],
    correctAnswer: 2,
    explanation: "Excel affiche cette erreur quand une formule tente de diviser un nombre par zéro ou une cellule vide.",
    trap: "Confondre avec #VALEUR! qui concerne souvent le texte.",
    tip: "DIV porte bien son nom : Division.",
  },

  // --- OPÉRATIONNEL (Données) ---
  {
    id: 8,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Quelle fonction permet de chercher la valeur 10 dans la colonne A et renvoyer le résultat de la colonne B ?",
    correctAnswer: "=RECHERCHEV(10;A:B;2;FAUX)",
    explanation: "RECHERCHEV cherche verticalement dans la 1ère colonne de la plage.",
    trap: "Oublier le 'FAUX' pour une recherche exacte.",
    tip: "RECHERCHEV(Quoi; Oû; Colonne; Précision).",
  },
  {
    id: 9,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Dans un Tableau Croisé Dynamique, où placez-vous un champ pour voir les sommes cumulées ?",
    options: ["Lignes", "Colonnes", "Valeurs", "Filtres"],
    correctAnswer: 2,
    explanation: "La zone 'Valeurs' est destinée aux calculs (sommes, moyennes, nb).",
    trap: "Mettre le champ dans 'Lignes' affichera les noms, pas les calculs.",
    tip: "Valeurs = Calculs.",
  },

  // --- AVANCÉ (Calculs) ---
  {
    id: 10,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Saisissez la formule pour joindre le texte de A1 ('Jean') et B1 ('Dupont') avec un espace entre les deux.",
    correctAnswer: "=A1&\" \"&B1",
    explanation: "L'esperluette (&) permet de concaténer (lier) des éléments.",
    trap: "Oublier l'espace entre guillemets \" \".",
    tip: "& = ET.",
  },
  {
    id: 11,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment arrondir la valeur de A1 à 2 décimales ?",
    correctAnswer: "=ARRONDI(A1;2)",
    explanation: "La fonction ARRONDI prend la valeur et le nombre de chiffres après la virgule.",
    trap: "Le format 'Monétaire' réduit l'affichage mais pas la valeur réelle calculée.",
    tip: "Vrai arrondi = Fonction ARRONDI.",
  },

  // --- AVANCÉ (Données/Tableau) ---
  {
    id: 12,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Quel outil permet de supprimer les doublons dans une liste ?",
    options: ["Filtre", "Validation des données", "Supprimer les doublons (onglet Données)", "Consolider"],
    correctAnswer: 2,
    explanation: "Le bouton 'Supprimer les doublons' nettoie proprement les listes.",
    trap: "Le filtre 'Valeurs uniques' ne fait que masquer, il ne supprime pas.",
    tip: "Cliquez sur 'Données' puis l'icône avec des barres bleues barrées.",
  },

  // --- EXPERT (Calculs/Logique) ---
  {
    id: 13,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Écrivez une formule : Si A1 > 10, affiche 'OK', sinon 'KO'.",
    correctAnswer: "=SI(A1>10;\"OK\";\"KO\")",
    explanation: "Fonction SI(Test ; Si Vrai ; Si Faux).",
    trap: "Inverser le point-virgule et la virgule selon la version.",
    tip: "Le texte doit toujours être entre guillemets \" \".",
  },
  {
    id: 14,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Quelle fonction permet de compter le nombre de cellules NON vides dans une plage A1:A10 ?",
    correctAnswer: "=NBVAL(A1:A10)",
    explanation: "NBVAL compte tout (texte et nombres), contrairement à NB qui ne compte que les nombres.",
    trap: "Utiliser NB() s'il y a du texte dans la colonne.",
    tip: "NBVAL = NB Valeurs.",
  },

  // --- DIVERS (Ajout pour atteindre 35 questions) ---
  {
    id: 15,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quel raccourci permet d'annuler la dernière action ?",
    options: ["Ctrl + C", "Ctrl + V", "Ctrl + Z", "Ctrl + Y"],
    correctAnswer: 2,
    explanation: "Ctrl + Z est le raccourci universel pour annuler.",
    trap: "Ctrl + Y qui sert à rétablir (l'inverse).",
    tip: "Z comme 'Zut, je me suis trompé'.",
  },
  {
    id: 16,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Où se trouve la 'Mise en forme conditionnelle' ?",
    options: ["Onglet Insertion", "Onglet Accueil", "Onglet Données", "Onglet Révision"],
    correctAnswer: 1,
    explanation: "Elle se trouve en plein milieu de l'onglet Accueil, groupe 'Styles'.",
    trap: "Chercher dans 'Mise en page'.",
    tip: "C'est un outil de style, donc Accueil.",
  },
  {
    id: 17,
    domain: Domain.Calculs,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Comment obtenir la date du jour de façon dynamique ?",
    correctAnswer: "=AUJOURDHUI()",
    explanation: "La fonction renvoie la date système et se met à jour chaque jour.",
    trap: "Oublier les parenthèses vides ().",
    tip: "Pas d'argument à l'intérieur des parenthèses.",
  },
  {
    id: 18,
    domain: Domain.Donnees,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Formule pour compter combien d'élèves ont plus de 10 en B2:B10 ?",
    correctAnswer: "=NB.SI(B2:B10;\">10\")",
    explanation: "NB.SI compte selon un critère.",
    trap: "Oublier les guillemets autour du critère \">10\".",
    tip: "Critère texte = Guis.",
  },
  {
    id: 19,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Quelle touche fige une référence (ajoute des $) dans une formule ?",
    options: ["F2", "F4", "F8", "F12"],
    correctAnswer: 1,
    explanation: "Appuyer sur F4 transforme A1 en $A$1.",
    trap: "Taper les $ manuellement au clavier.",
    tip: "F4 = Dollars.",
  },
  {
    id: 20,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Extraire les 3 chiffres de gauche de la cellule A1.",
    correctAnswer: "=GAUCHE(A1;3)",
    explanation: "Fonction GAUCHE(Cellule ; Nb caractères).",
    trap: "Utiliser DROITE si on veut la fin du texte.",
    tip: "GAUCHE pour le début.",
  },
  {
    id: 21,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Comment fusionner deux cellules ?",
    options: ["Clic droit > Fusionner", "Bouton Fusionner et centrer (onglet Accueil)", "Onglet Insertion > Fusion", "On ne peut pas"],
    correctAnswer: 1,
    explanation: "L'option standard est dans l'onglet Accueil.",
    trap: "Fusionner fait perdre les données de toutes les cellules sauf la première.",
    tip: "À utiliser avec parcimonie pour les titres.",
  },
  {
    id: 22,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Raccourci pour transformer une plage en 'Tableau Excel' ?",
    correctAnswer: "Ctrl+T",
    explanation: "C'est le raccourci vers l'objet Tableau structuré.",
    trap: "Confondre avec Ctrl+L (qui marche aussi mais moins connu).",
    tip: "T pour Tableau.",
  },
  {
     id: 23,
     domain: Domain.Calculs,
     difficulty: Difficulty.Moyen,
     type: QuestionType.Practical,
     text: "Si A1 contient 'POMME', transformez-le en minuscules.",
     correctAnswer: "=MINUSCULE(A1)",
     explanation: "La fonction MINUSCULE convertit toute la chaîne.",
     trap: "Il n'y a pas de fonction 'PETIT' pour le texte.",
     tip: "MAJUSCULE / MINUSCULE.",
  },
  {
    id: 24,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Fonction pour chercher une valeur si RECHERCHEV ne suffit pas (recherche à gauche) ?",
    options: ["RECHERCHEX", "INDEX+EQUIV", "RECHERCHEH", "Les deux premières sont correctes"],
    correctAnswer: 3,
    explanation: "Sur Excel 365, RECHERCHEX remplace tout. Avant, on utilisait INDEX et EQUIV.",
    trap: "RECHERCHEV ne sait pas regarder à gauche de sa colonne de recherche.",
    tip: "RECHERCHEX est le nouveau couteau suisse.",
  },
  {
    id: 25,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Comment insérer un commentaire sur une cellule ?",
    options: ["Onglet Insertion", "Clic droit > Nouveau commentaire", "Onglet Révision", "Toutes ces réponses sont correctes"],
    correctAnswer: 3,
    explanation: "Plusieurs chemins mènent aux commentaires/notes.",
    trap: "Confondre 'Note' et 'Commentaire' (fil de discussion).",
    tip: "Clic droit est le plus rapide.",
  },
  {
    id: 26,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Si A1=10 et B1=20, formule pour tester si les deux sont > 5.",
    correctAnswer: "=ET(A1>5;B1>5)",
    explanation: "La fonction ET renvoie VRAI si TOUS les tests sont vrais.",
    trap: "Utiliser OU() si on n'en veut qu'un seul des deux.",
    tip: "ET = Toutes les conditions.",
  },
  {
    id: 27,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment figer uniquement la première colonne ?",
    correctAnswer: "Affichage > Figer les volets > Figer la première colonne",
    explanation: "Option spécifique du menu Figer les volets.",
    trap: "Figer la ligne supérieure figera le haut, pas le côté.",
    tip: "Menu Affichage.",
  },
  {
    id: 28,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment créer un menu déroulant dans une cellule ?",
    correctAnswer: "Données > Validation des données > Liste",
    explanation: "On choisit 'Liste' et on saisit les sources.",
    trap: "Taper les noms séparés par des virgules (souvent des points-virgules selon Windows).",
    tip: "Validation = Contrôle ce qu'on saisit.",
  },
  {
    id: 29,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Sommer B1:B10 seulement si A1:A10 contient 'Sud'.",
    correctAnswer: "=SOMME.SI(A1:A10;\"Sud\";B1:B10)",
    explanation: "SOMME.SI(Plage_Critère ; Critère ; Plage_Somme).",
    trap: "Inverser les plages.",
    tip: "Où je cherche ? Quoi ? Qu'est-ce que je compte ?",
  },
  {
    id: 30,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Quel est le signe de début de formule ?",
    correctAnswer: "=",
    explanation: "Obligatoire pour qu'Excel reconnaisse un calcul.",
    trap: "L'oubli.",
    tip: "Égal.",
  },
  {
    id: 31,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment masquer les quadrillages à l'écran ?",
    correctAnswer: "Affichage > Décocher Quadrillage",
    explanation: "Nettoie le visuel pour une présentation.",
    trap: "Peindre tout en blanc (mauvaise pratique).",
    tip: "Onglet Affichage.",
  },
  {
    id: 32,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment obtenir l'année de la date en A1 ?",
    correctAnswer: "=ANNEE(A1)",
    explanation: "La fonction ANNEE extrait l'année d'une cellule au format Date.",
    trap: "La cellule doit bien être au format Date.",
    tip: "ANNEE().",
  },
  {
    id: 33,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Peut-on insérer un graphique DANS une cellule ?",
    options: ["Non, impossible", "Oui, avec les Graphiques Sparkline", "Oui, avec une macro", "Uniquement avec des images"],
    correctAnswer: 1,
    explanation: "Les Sparklines sont des mini-graphiques qui tiennent dans une cellule.",
    trap: "Le graphique standard flotte au-dessus des cellules.",
    tip: "Sparkline = mini graphique.",
  },
  {
    id: 34,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Si A1=5, résultat de =A1^2 ?",
    correctAnswer: "25",
    explanation: "^ est l'opérateur de puissance.",
    trap: "Confondre avec multiplication.",
    tip: "Puissance.",
  },
  {
    id: 35,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Comment enregistrer un fichier en PDF ?",
    options: ["Fichier > Exporter", "Fichier > Enregistrer sous > Choisir PDF", "Fichier > Imprimer > Imprimante PDF", "Toutes ces réponses sont correctes"],
    correctAnswer: 3,
    explanation: "Excel offre plusieurs chemins pour créer un PDF.",
    trap: "Le PDF n'est plus modifiable dans Excel par la suite.",
    tip: "L'export est le plus direct.",
  }
];

export const getQuestionsByLevel = (level: TosaLevel, count: number) => {
  let ratioM = 0.2;
  if (level === TosaLevel.Operationnel) ratioM = 0.4;
  if (level === TosaLevel.Avance) ratioM = 0.55;
  if (level === TosaLevel.Expert) ratioM = 0.7;

  const countM = Math.round(count * ratioM);
  const countF = count - countM;

  const facile = QUESTIONS.filter(q => q.difficulty === Difficulty.Facile);
  const moyen = QUESTIONS.filter(q => q.difficulty === Difficulty.Moyen);

  const shuffledF = [...facile].sort(() => 0.5 - Math.random());
  const shuffledM = [...moyen].sort(() => 0.5 - Math.random());

  const result = [...shuffledF.slice(0, countF), ...shuffledM.slice(0, countM)];
  return result.sort((a, b) => {
    if (a.difficulty === b.difficulty) return 0.5 - Math.random();
    return a.difficulty === Difficulty.Facile ? -1 : 1;
  });
};

