import { Domain, Difficulty, QuestionType, Question, TosaLevel } from './types';

export const QUESTIONS: Question[] = [
  // --- INITIAL / BASIQUE (Environnement) ---
  {
    id: 1,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Dans quel onglet du ruban se trouve la fonction 'Figer les volets' ?",
    options: ["Accueil", "Insertion", "Mise en page", "Affichage"],
    correctAnswer: 3,
    explanation: "L'onglet 'Affichage' regroupe les options de visualisation. Figer les volets permet de garder les titres visibles.",
    trap: "Chercher dans 'Mise en page' (réservé à l'impression).",
    tip: "Visualisation = Affichage.",
  },
  {
    id: 2,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quel bouton permet de copier uniquement la mise en forme d'une cellule ?",
    options: ["Copier", "Pinceau (Reproduire la mise en forme)", "Coller", "Remplissage"],
    correctAnswer: 1,
    explanation: "L'icône du pinceau copie la couleur, la police et les bordures sans copier le texte.",
    trap: "Le bouton 'Copier' standard prend tout le contenu.",
    tip: "Un clic simple pour une fois, double-clic pour plusieurs fois.",
  },

  // --- INITIAL / BASIQUE (Calculs) ---
  {
    id: 3,
    domain: Domain.Calculs,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quelle formule est correcte pour faire la somme des cellules A1 et A2 ?",
    options: ["=A1+A2", "=SOMME(A1:A2)", "A1+A2", "Les deux premières sont correctes"],
    correctAnswer: 3,
    explanation: "Toute formule doit commencer par '='. On peut utiliser '+' ou la fonction SOMME.",
    trap: "Oublier le signe égal (=).",
    tip: "Pas d'égal, pas de calcul !",
  },
  {
    id: 4,
    domain: Domain.Calculs,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Écrivez la fonction pour trouver la valeur la plus basse dans la plage B2:B20.",
    correctAnswer: "=MIN(B2:B20)",
    explanation: "La fonction MIN renvoie le minimum d'une série de valeurs.",
    trap: "Confondre avec 'PETIT.VALEUR' qui demande plus de paramètres.",
    tip: "MIN pour minimum, MAX pour maximum.",
  },

  // --- INITIAL / BASIQUE (Mise en forme) ---
  {
    id: 5,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quel format appliquer pour afficher '0,25' sous la forme '25%' ?",
    options: ["Format Texte", "Format Nombre", "Format Pourcentage", "Format Comptabilité"],
    correctAnswer: 2,
    explanation: "Le format pourcentage multiplie visuellement la valeur par 100 et ajoute le symbole %.",
    trap: "Taper '%' manuellement transforme le chiffre en texte.",
    tip: "Utilisez le bouton '%' dans l'onglet Accueil.",
  },

  // --- OPÉRATIONNEL (Calculs) ---
  {
    id: 6,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "A1=100. Écrivez la formule pour calculer une remise de 15% sur ce montant.",
    correctAnswer: "=A1*0,15",
    explanation: "Multiplier par 0,15 donne le montant de la remise (15/100).",
    trap: "Multiplier par 1,15 (ce qui ajouterait 15% au lieu de calculer la remise).",
    tip: "X% = multiplier par X/100.",
  },
  {
    id: 7,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Que signifie l'erreur #DIV/0! ?",
    options: ["La cellule est trop petite", "La formule contient du texte", "Division par zéro", "Référence de cellule introuvable"],
    correctAnswer: 2,
    explanation: "Excel affiche cette erreur quand une formule tente de diviser un nombre par zéro ou une cellule vide.",
    trap: "Confondre avec #VALEUR! qui concerne souvent le texte.",
    tip: "DIV porte bien son nom : Division.",
  },

  // --- OPÉRATIONNEL (Données) ---
  {
    id: 8,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Quelle fonction permet de chercher la valeur 10 dans la colonne A et renvoyer le résultat de la colonne B ?",
    correctAnswer: "=RECHERCHEV(10;A:B;2;FAUX)",
    explanation: "RECHERCHEV cherche verticalement dans la 1ère colonne de la plage.",
    trap: "Oublier le 'FAUX' pour une recherche exacte.",
    tip: "RECHERCHEV(Quoi; Oû; Colonne; Précision).",
  },
  {
    id: 9,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Dans un Tableau Croisé Dynamique, où placez-vous un champ pour voir les sommes cumulées ?",
    options: ["Lignes", "Colonnes", "Valeurs", "Filtres"],
    correctAnswer: 2,
    explanation: "La zone 'Valeurs' est destinée aux calculs (sommes, moyennes, nb).",
    trap: "Mettre le champ dans 'Lignes' affichera les noms, pas les calculs.",
    tip: "Valeurs = Calculs.",
  },

  // --- AVANCÉ (Calculs) ---
  {
    id: 10,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Saisissez la formule pour joindre le texte de A1 ('Jean') et B1 ('Dupont') avec un espace entre les deux.",
    correctAnswer: "=A1&\" \"&B1",
    explanation: "L'esperluette (&) permet de concaténer (lier) des éléments.",
    trap: "Oublier l'espace entre guillemets \" \".",
    tip: "& = ET.",
  },
  {
    id: 11,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment arrondir la valeur de A1 à 2 décimales ?",
    correctAnswer: "=ARRONDI(A1;2)",
    explanation: "La fonction ARRONDI prend la valeur et le nombre de chiffres après la virgule.",
    trap: "Le format 'Monétaire' réduit l'affichage mais pas la valeur réelle calculée.",
    tip: "Vrai arrondi = Fonction ARRONDI.",
  },

  // --- AVANCÉ (Données/Tableau) ---
  {
    id: 12,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Quel outil permet de supprimer les doublons dans une liste ?",
    options: ["Filtre", "Validation des données", "Supprimer les doublons (onglet Données)", "Consolider"],
    correctAnswer: 2,
    explanation: "Le bouton 'Supprimer les doublons' nettoie proprement les listes.",
    trap: "Le filtre 'Valeurs uniques' ne fait que masquer, il ne supprime pas.",
    tip: "Cliquez sur 'Données' puis l'icône avec des barres bleues barrées.",
  },

  // --- EXPERT (Calculs/Logique) ---
  {
    id: 13,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Écrivez une formule : Si A1 > 10, affiche 'OK', sinon 'KO'.",
    correctAnswer: "=SI(A1>10;\"OK\";\"KO\")",
    explanation: "Fonction SI(Test ; Si Vrai ; Si Faux).",
    trap: "Inverser le point-virgule et la virgule selon la version.",
    tip: "Le texte doit toujours être entre guillemets \" \".",
  },
  {
    id: 14,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Quelle fonction permet de compter le nombre de cellules NON vides dans une plage A1:A10 ?",
    correctAnswer: "=NBVAL(A1:A10)",
    explanation: "NBVAL compte tout (texte et nombres), contrairement à NB qui ne compte que les nombres.",
    trap: "Utiliser NB() s'il y a du texte dans la colonne.",
    tip: "NBVAL = NB Valeurs.",
  },

  // --- DIVERS (Ajout pour atteindre 35 questions) ---
  {
    id: 15,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quel raccourci permet d'annuler la dernière action ?",
    options: ["Ctrl + C", "Ctrl + V", "Ctrl + Z", "Ctrl + Y"],
    correctAnswer: 2,
    explanation: "Ctrl + Z est le raccourci universel pour annuler.",
    trap: "Ctrl + Y qui sert à rétablir (l'inverse).",
    tip: "Z comme 'Zut, je me suis trompé'.",
  },
  {
    id: 16,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Où se trouve la 'Mise en forme conditionnelle' ?",
    options: ["Onglet Insertion", "Onglet Accueil", "Onglet Données", "Onglet Révision"],
    correctAnswer: 1,
    explanation: "Elle se trouve en plein milieu de l'onglet Accueil, groupe 'Styles'.",
    trap: "Chercher dans 'Mise en page'.",
    tip: "C'est un outil de style, donc Accueil.",
  },
  {
    id: 17,
    domain: Domain.Calculs,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Comment obtenir la date du jour de façon dynamique ?",
    correctAnswer: "=AUJOURDHUI()",
    explanation: "La fonction renvoie la date système et se met à jour chaque jour.",
    trap: "Oublier les parenthèses vides ().",
    tip: "Pas d'argument à l'intérieur des parenthèses.",
  },
  {
    id: 18,
    domain: Domain.Donnees,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Formule pour compter combien d'élèves ont plus de 10 en B2:B10 ?",
    correctAnswer: "=NB.SI(B2:B10;\">10\")",
    explanation: "NB.SI compte selon un critère.",
    trap: "Oublier les guillemets autour du critère \">10\".",
    tip: "Critère texte = Guis.",
  },
  {
    id: 19,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Quelle touche fige une référence (ajoute des $) dans une formule ?",
    options: ["F2", "F4", "F8", "F12"],
    correctAnswer: 1,
    explanation: "Appuyer sur F4 transforme A1 en $A$1.",
    trap: "Taper les $ manuellement au clavier.",
    tip: "F4 = Dollars.",
  },
  {
    id: 20,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Extraire les 3 chiffres de gauche de la cellule A1.",
    correctAnswer: "=GAUCHE(A1;3)",
    explanation: "Fonction GAUCHE(Cellule ; Nb caractères).",
    trap: "Utiliser DROITE si on veut la fin du texte.",
    tip: "GAUCHE pour le début.",
  },
  {
    id: 21,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Comment fusionner deux cellules ?",
    options: ["Clic droit > Fusionner", "Bouton Fusionner et centrer (onglet Accueil)", "Onglet Insertion > Fusion", "On ne peut pas"],
    correctAnswer: 1,
    explanation: "L'option standard est dans l'onglet Accueil.",
    trap: "Fusionner fait perdre les données de toutes les cellules sauf la première.",
    tip: "À utiliser avec parcimonie pour les titres.",
  },
  {
    id: 22,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Raccourci pour transformer une plage en 'Tableau Excel' ?",
    correctAnswer: "Ctrl+T",
    explanation: "C'est le raccourci vers l'objet Tableau structuré.",
    trap: "Confondre avec Ctrl+L (qui marche aussi mais moins connu).",
    tip: "T pour Tableau.",
  },
  {
     id: 23,
     domain: Domain.Calculs,
     difficulty: Difficulty.Moyen,
     type: QuestionType.Practical,
     text: "Si A1 contient 'POMME', transformez-le en minuscules.",
     correctAnswer: "=MINUSCULE(A1)",
     explanation: "La fonction MINUSCULE convertit toute la chaîne.",
     trap: "Il n'y a pas de fonction 'PETIT' pour le texte.",
     tip: "MAJUSCULE / MINUSCULE.",
  },
  {
    id: 24,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Fonction pour chercher une valeur si RECHERCHEV ne suffit pas (recherche à gauche) ?",
    options: ["RECHERCHEX", "INDEX+EQUIV", "RECHERCHEH", "Les deux premières sont correctes"],
    correctAnswer: 3,
    explanation: "Sur Excel 365, RECHERCHEX remplace tout. Avant, on utilisait INDEX et EQUIV.",
    trap: "RECHERCHEV ne sait pas regarder à gauche de sa colonne de recherche.",
    tip: "RECHERCHEX est le nouveau couteau suisse.",
  },
  {
    id: 25,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Comment insérer un commentaire sur une cellule ?",
    options: ["Onglet Insertion", "Clic droit > Nouveau commentaire", "Onglet Révision", "Toutes ces réponses sont correctes"],
    correctAnswer: 3,
    explanation: "Plusieurs chemins mènent aux commentaires/notes.",
    trap: "Confondre 'Note' et 'Commentaire' (fil de discussion).",
    tip: "Clic droit est le plus rapide.",
  },
  {
    id: 26,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Si A1=10 et B1=20, formule pour tester si les deux sont > 5.",
    correctAnswer: "=ET(A1>5;B1>5)",
    explanation: "La fonction ET renvoie VRAI si TOUS les tests sont vrais.",
    trap: "Utiliser OU() si on n'en veut qu'un seul des deux.",
    tip: "ET = Toutes les conditions.",
  },
  {
    id: 27,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment figer uniquement la première colonne ?",
    correctAnswer: "Affichage > Figer les volets > Figer la première colonne",
    explanation: "Option spécifique du menu Figer les volets.",
    trap: "Figer la ligne supérieure figera le haut, pas le côté.",
    tip: "Menu Affichage.",
  },
  {
    id: 28,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment créer un menu déroulant dans une cellule ?",
    correctAnswer: "Données > Validation des données > Liste",
    explanation: "On choisit 'Liste' et on saisit les sources.",
    trap: "Taper les noms séparés par des virgules (souvent des points-virgules selon Windows).",
    tip: "Validation = Contrôle ce qu'on saisit.",
  },
  {
    id: 29,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Sommer B1:B10 seulement si A1:A10 contient 'Sud'.",
    correctAnswer: "=SOMME.SI(A1:A10;\"Sud\";B1:B10)",
    explanation: "SOMME.SI(Plage_Critère ; Critère ; Plage_Somme).",
    trap: "Inverser les plages.",
    tip: "Où je cherche ? Quoi ? Qu'est-ce que je compte ?",
  },
  {
    id: 30,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Quel est le signe de début de formule ?",
    correctAnswer: "=",
    explanation: "Obligatoire pour qu'Excel reconnaisse un calcul.",
    trap: "L'oubli.",
    tip: "Égal.",
  },
  {
    id: 31,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment masquer les quadrillages à l'écran ?",
    correctAnswer: "Affichage > Décocher Quadrillage",
    explanation: "Nettoie le visuel pour une présentation.",
    trap: "Peindre tout en blanc (mauvaise pratique).",
    tip: "Onglet Affichage.",
  },
  {
    id: 32,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment obtenir l'année de la date en A1 ?",
    correctAnswer: "=ANNEE(A1)",
    explanation: "La fonction ANNEE extrait l'année d'une cellule au format Date.",
    trap: "La cellule doit bien être au format Date.",
    tip: "ANNEE().",
  },
  {
    id: 33,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Peut-on insérer un graphique DANS une cellule ?",
    options: ["Non, impossible", "Oui, avec les Graphiques Sparkline", "Oui, avec une macro", "Uniquement avec des images"],
    correctAnswer: 1,
    explanation: "Les Sparklines sont des mini-graphiques qui tiennent dans une cellule.",
    trap: "Le graphique standard flotte au-dessus des cellules.",
    tip: "Sparkline = mini graphique.",
  },
  {
    id: 34,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Si A1=5, résultat de =A1^2 ?",
    correctAnswer: "25",
    explanation: "^ est l'opérateur de puissance.",
    trap: "Confondre avec multiplication.",
    tip: "Puissance.",
  },
  {
    id: 35,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Comment enregistrer un fichier en PDF ?",
    options: ["Fichier > Exporter", "Fichier > Enregistrer sous > Choisir PDF", "Fichier > Imprimer > Imprimante PDF", "Toutes ces réponses sont correctes"],
    correctAnswer: 3,
    explanation: "Excel offre plusieurs chemins pour créer un PDF.",
    trap: "Le PDF n'est plus modifiable dans Excel par la suite.",
    tip: "L'export est le plus direct.",
  },
  {
    id: 36,
    domain: Domain.Calculs,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quelle fonction permet de compter le nombre de cellules contenant uniquement des nombres ?",
    options: ["NB", "NBVAL", "NB.SI", "NB.VIDE"],
    correctAnswer: 0,
    explanation: "La fonction NB compte les cellules contenant des nombres dans une plage.",
    trap: "Utiliser NBVAL qui compte toutes les cellules non vides (texte inclus).",
    tip: "NB pour Nombres.",
  },
  {
    id: 37,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Comment sélectionner toute une colonne d'un seul clic ?",
    options: ["Cliquer sur la première cellule", "Cliquer sur la lettre de l'en-tête de colonne", "Double-cliquer sur une cellule", "Appuyer sur F1"],
    correctAnswer: 1,
    explanation: "Cliquer sur la lettre (A, B, C...) sélectionne la colonne entière.",
    trap: "L'en-tête de ligne sélectionne la ligne, pas la colonne.",
    tip: "Lettre = Colonne, Chiffre = Ligne.",
  },
  {
    id: 38,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quel bouton permet d'ajuster le texte pour qu'il s'affiche sur plusieurs lignes dans une même cellule ?",
    options: ["Fusionner", "Renvoyer à la ligne automatiquement", "Centrer", "Augmenter le retrait"],
    correctAnswer: 1,
    explanation: "Cette option évite que le texte ne dépasse sur les cellules voisines.",
    trap: "Confondre avec 'Fusionner' qui regroupe plusieurs cellules.",
    tip: "Renvoyer = Retour à la ligne.",
  },
  {
    id: 39,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Saisissez la formule pour calculer la moyenne de la plage D1 à D100.",
    correctAnswer: "=MOYENNE(D1:D100)",
    explanation: "La fonction MOYENNE calcule la moyenne arithmétique.",
    trap: "Oublier le 'NE' à la fin de MOYENNE (MOYEN n'existe pas en FR).",
    tip: "Le nom complet : MOYENNE.",
  },
  {
    id: 40,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Pour filtrer des données selon plusieurs critères complexes (Ex: Ventes > 1000 ET Ville = Paris), quel outil est le plus adapté ?",
    options: ["Filtre automatique", "Filtre avancé", "Rechercher", "Trier"],
    correctAnswer: 1,
    explanation: "Le filtre avancé (ou 'Advanced Filter') permet d'extraire des données selon une zone de critères séparée.",
    trap: "Le filtre classique peut le faire via les menus, mais le filtre avancé est plus puissant pour l'extraction.",
    tip: "Onglet Données > Avancé.",
  },
  {
    id: 41,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Si A1=10 et B1=0, quel sera le résultat de =SI(B1=0;\"Erreur\";A1/B1) ?",
    correctAnswer: "Erreur",
    explanation: "Le test B1=0 est vrai, donc Excel renvoie la valeur 'Si vrai'.",
    trap: "Penser qu'Excel fera quand même la division (il ne la fait pas si le test l'évite).",
    tip: "Le SI protège contre les erreurs de calcul.",
  },
  {
    id: 42,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Quel caractère sépare les arguments d'une fonction dans la version française d'Excel ?",
    correctAnswer: ";",
    explanation: "Le point-virgule est le séparateur standard en France.",
    trap: "Utiliser une virgule (standard US).",
    tip: "Point-virgule ; ",
  },
  {
    id: 43,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Quelle fonction permet de transformer en MAJUSCULE le texte de la cellule A5 ?",
    correctAnswer: "=MAJUSCULE(A5)",
    explanation: "La fonction MAJUSCULE passe tout le texte en capitales.",
    trap: "Essayer de changer la police (cela ne change pas la valeur réelle).",
    tip: "MAJUSCULE().",
  },
  {
    id: 44,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Comment appliquer une barre de données (graphique interne) dans des cellules ?",
    options: ["Insertion > Graphique", "Mise en forme conditionnelle > Barres de données", "Format de cellule > Remplissage", "Dessiner une forme"],
    correctAnswer: 1,
    explanation: "C'est une option de la MFC qui permet de visualiser les proportions directement.",
    trap: "Les graphiques Sparkline sont différents (ce sont des lignes/colonnes, pas un remplissage de cellule).",
    tip: "MFC = Couleur ou Forme selon la valeur.",
  },
  {
    id: 45,
    domain: Domain.Donnees,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quel onglet contient les outils pour importer des données depuis un fichier texte ou CSV ?",
    options: ["Accueil", "Insertion", "Données", "Révision"],
    correctAnswer: 2,
    explanation: "L'onglet Données est le centre névralgique pour 'Obtenir et transformer les données'.",
    trap: "L'onglet 'Fichier' permet d'ouvrir, mais 'Données' permet d'importer proprement.",
    tip: "Données externes = Onglet Données.",
  },
  {
    id: 46,
    domain: Domain.Calculs,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Formule pour calculer 20% de la valeur en B10.",
    correctAnswer: "=B10*0,2",
    explanation: "Cela revient à faire B10 * (20/100).",
    trap: "Multiplier par 1,2 (ce qui ajouterait 20% au lieu de calculer juste la part).",
    tip: "X% = 0,X.",
  },
  {
    id: 47,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Quel raccourci permet d'insérer rapidement la somme automatique sur une cellule ?",
    options: ["Alt + =", "Ctrl + S", "Alt + S", "Ctrl + +"],
    correctAnswer: 0,
    explanation: "Alt + = (ou Alt + MAJ + = selon le clavier) insère la fonction SOMME en devinant la plage.",
    trap: "Ctrl + S qui sert à enregistrer (Save).",
    tip: "Raccourci magique pour les bilans.",
  },
  {
    id: 48,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Extraire les 5 caractères du milieu de A1, en commençant au 2ème caractère.",
    correctAnswer: "=STXT(A1;2;5)",
    explanation: "STXT(Texte ; Position_Départ ; Nb_caractères).",
    trap: "Confondre l'ordre des chiffres.",
    tip: "S-T-X-T : Source, Temps (Départ), X (Taille).",
  },
  {
    id: 49,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Quel format de cellule utiliser pour que '1234' s'affiche '1 234,00 €' ?",
    correctAnswer: "Monétaire",
    explanation: "Le format monétaire ajoute le séparateur de milliers, les décimales et le symbole devise.",
    trap: "Le format 'Comptabilité' fait presque la même chose mais aligne les symboles € à gauche.",
    tip: "Utilisez le bouton raccourci dans l'onglet Accueil.",
  },
  {
    id: 50,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Dans un TCD, comment changer une 'Somme' en 'Moyenne' ?",
    correctAnswer: "Paramètres des champs de valeurs",
    explanation: "Il faut cliquer sur le champ dans la zone Valeurs et choisir l'option de synthèse.",
    trap: "Changer la formule dans la barre de formule (impossible dans un TCD).",
    tip: "Clic droit sur une valeur > Synthétiser les valeurs par.",
  },
  {
    id: 51,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Que renvoie la formule =NB.SI(A1:A10;\">\"&MOYENNE(A1:A10)) ?",
    options: ["Une erreur", "Le nombre de valeurs supérieures à la moyenne", "La moyenne des valeurs", "Rien"],
    correctAnswer: 1,
    explanation: "On peut concaténer un comparateur et une fonction pour créer un critère dynamique.",
    trap: "Oublier l'esperluette (&) pour lier le \">\" et la fonction.",
    tip: "Critères dynamiques = &.",
  },
  {
    id: 52,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Comment renommer une feuille de calcul ?",
    options: ["Double-clic sur l'onglet en bas", "Fichier > Renommer", "Alt + F4", "Clic droit sur une cellule > Renommer"],
    correctAnswer: 0,
    explanation: "Le double-clic sur l'onglet permet de modifier le nom directement.",
    trap: "Confondre avec le nom du fichier.",
    tip: "Double-clic en bas à gauche.",
  },
  {
    id: 53,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Si A1=15. Formule : si A1 est compris entre 10 et 20, afficher 'OUI', sinon 'NON'.",
    correctAnswer: "=SI(ET(A1>=10;A1<=20);\"OUI\";\"NON\")",
    explanation: "On utilise ET() à l'intérieur du SI().",
    trap: "Essayer de faire 10<A1<20, ce qu'Excel ne comprend pas ainsi.",
    tip: "Besoin de 2 conditions = ET().",
  },
  {
    id: 54,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment répéter les titres d'un tableau sur chaque page à l'impression ?",
    correctAnswer: "Mise en page > Imprimer les titres",
    explanation: "L'option 'Lignes à répéter en haut' permet de garder les en-têtes visibles sur papier.",
    trap: "Figer les volets (cela ne sert qu'à l'écran).",
    tip: "Impression = Onglet Mise en page.",
  },
  {
    id: 55,
    domain: Domain.Donnees,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quel bouton cliquer pour réorganiser une liste du plus grand au plus petit ?",
    options: ["Trier de A à Z", "Trier de Z à A", "Filtre", "Rechercher"],
    correctAnswer: 1,
    explanation: "Z à A correspond à l'ordre décroissant.",
    trap: "A à Z est l'ordre croissant.",
    tip: "Z->A = Descendant.",
  },
  {
    id: 56,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Formule pour obtenir le numéro du jour du mois de la date en A1.",
    correctAnswer: "=JOUR(A1)",
    explanation: "La fonction JOUR renvoie un nombre de 1 à 31.",
    trap: "Confondre avec JOURS qui calcule un écart entre deux dates.",
    tip: "JOUR(), MOIS(), ANNEE().",
  },
  {
    id: 57,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Raccourci pour vérifier l'orthographe du classeur ?",
    correctAnswer: "F7",
    explanation: "F7 lance le vérificateur orthographique.",
    trap: "Chercher dans l'onglet Accueil (c'est dans Révision).",
    tip: "F7.",
  },
  {
    id: 58,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Supprimer les espaces inutiles au début et à la fin d'un texte en A1.",
    correctAnswer: "=SUPPRESPACE(A1)",
    explanation: "Nettoie les espaces de trop (souvent après un import).",
    trap: "Cette fonction ne supprime pas les espaces simples entre les mots.",
    tip: "Nettoyage = SUPPRESPACE.",
  },
  {
    id: 59,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quelle couleur de remplissage par défaut possède une cellule Excel ?",
    options: ["Blanc", "Aucun remplissage (Transparent)", "Gris clair", "Jaune"],
    correctAnswer: 1,
    explanation: "Par défaut, les cellules n'ont aucun remplissage, on voit le quadrillage par transparence.",
    trap: "Penser que c'est blanc (si vous peignez en blanc, vous perdez le quadrillage).",
    tip: "Aucun remplissage.",
  },
  {
    id: 60,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Comment grouper des dates par 'Mois' dans un Tableau Croisé Dynamique ?",
    options: ["Trier par date", "Clic droit sur une date > Grouper", "Ajouter un segment", "On ne peut pas"],
    correctAnswer: 1,
    explanation: "L'option Grouper permet de regrouper les dates par jour, mois, trimestre ou année.",
    trap: "Le faire manuellement dans la source de données.",
    tip: "Clic droit > Grouper.",
  },
  {
    id: 61,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Si A1=10 et A2=20, formule pour tester si AU MOINS l'un des deux est > 15.",
    correctAnswer: "=OU(A1>15;A2>15)",
    explanation: "La fonction OU renvoie VRAI si au moins une condition est satisfaite.",
    trap: "Utiliser ET() qui demande que les deux soient vrais.",
    tip: "OU = L'un ou l'autre (ou les deux).",
  },
  {
    id: 62,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Que se passe-t-il si vous appuyez sur 'Entrée' après avoir saisi une valeur ?",
    options: ["La cellule reste sélectionnée", "La sélection descend d'une ligne", "La sélection va à droite", "Le fichier s'enregistre"],
    correctAnswer: 1,
    explanation: "C'est le comportement standard pour faciliter la saisie en colonne.",
    trap: "La touche 'Tab' va vers la droite.",
    tip: "Entrée = Bas.",
  },
  {
    id: 63,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Compter le nombre de fois où 'Paris' apparaît dans la plage A1:A50.",
    correctAnswer: "=NB.SI(A1:A50;\"Paris\")",
    explanation: "NB.SI(Plage ; Critère).",
    trap: "Oublier les guillemets autour de Paris.",
    tip: "Compte avec condition.",
  },
  {
    id: 64,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Quel outil permet de masquer des lignes selon leur contenu sans les supprimer ?",
    options: ["Supprimer", "Filtre", "Masquer", "Grouper"],
    correctAnswer: 1,
    explanation: "Le filtre masque les lignes qui ne correspondent pas aux critères.",
    trap: "La fonction 'Masquer' manuelle ne dépend pas du contenu.",
    tip: "Filtre = Masquage intelligent.",
  },
  {
    id: 65,
    domain: Domain.Calculs,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Formule pour multiplier A1 par B1.",
    correctAnswer: "=A1*B1",
    explanation: "L'astérisque * est l'opérateur de multiplication.",
    trap: "Utiliser 'x' du clavier.",
    tip: "*.",
  },
  {
    id: 66,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Trouver la valeur du milieu (médiane) dans la plage C1:C11.",
    correctAnswer: "=MEDIANE(C1:C11)",
    explanation: "La fonction MEDIANE renvoie la valeur centrale d'un jeu de données.",
    trap: "Confondre avec MOYENNE.",
    tip: "Milieu = MEDIANE.",
  },
  {
    id: 67,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quelle extension de fichier correspond à un classeur Excel standard (version moderne) ?",
    options: [".xls", ".xlsx", ".xlsm", ".csv"],
    correctAnswer: 1,
    explanation: ".xlsx est le format XML standard depuis Excel 2007.",
    trap: ".xlsm est réservé aux classeurs avec macros.",
    tip: "Le 'x' final pour XML.",
  },
  {
    id: 68,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Comment appliquer rapidement une bordure autour d'une sélection ?",
    options: ["Onglet Insertion > Bordure", "Bouton Bordures (onglet Accueil)", "Onglet Dessin", "On ne peut pas"],
    correctAnswer: 1,
    explanation: "Le menu déroulant des bordures est dans le groupe Police de l'onglet Accueil.",
    trap: "Chercher dans 'Mise en page'.",
    tip: "C'est de la décoration, donc Accueil.",
  },
  {
    id: 69,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment transformer une ligne en colonne (ou inversement) lors d'un collage ?",
    correctAnswer: "Collage spécial > Transposer",
    explanation: "L'option Transposer pivote les données de 90 degrés.",
    trap: "Le collage classique garde l'orientation d'origine.",
    tip: "Transposer = Pivoter.",
  },
  {
    id: 70,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Quelle fonction permet d'obtenir le reste d'une division entière de A1 par B1 ?",
    correctAnswer: "=MOD(A1;B1)",
    explanation: "La fonction MOD renvoie le modulo (le reste).",
    trap: "Essayer d'utiliser le signe % (qui est pour les pourcentages).",
    tip: "MOD comme Modulo.",
  },
  {
    id: 71,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Que permet de faire la 'Barre d'accès rapide' située tout en haut à gauche ?",
    options: ["Remplacer le ruban", "Accéder aux commandes favorites d'un clic", "Chercher sur internet", "Gérer les mots de passe"],
    correctAnswer: 1,
    explanation: "On peut y ajouter n'importe quelle commande (Enregistrer, Annuler, ou même Photos).",
    trap: "Elle ne remplace pas le ruban, elle le complète.",
    tip: "Personnalisez-la pour gagner du temps.",
  },
  {
    id: 72,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Formule pour arrondir A1 à l'entier supérieur le plus proche.",
    correctAnswer: "=ARRONDI.SUP(A1;0)",
    explanation: "Le second argument '0' indique qu'on ne veut pas de chiffres après la virgule.",
    trap: "Utiliser ENT() qui tronque mais n'arrondit pas forcément au supérieur.",
    tip: "ARRONDI.SUP.",
  },
  {
    id: 73,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Peut-on mettre en couleur uniquement les nombres négatifs automatiquement ?",
    options: ["Non", "Oui, avec un format de nombre personnalisé", "Oui, avec la Mise en forme conditionnelle", "Les deux réponses 'Oui' sont correctes"],
    correctAnswer: 3,
    explanation: "Le format de nombre (Rouge pour négatif) est rapide, la MFC est plus flexible.",
    trap: "Le faire manuellement (trop long et risqué).",
    tip: "MFC = Magie visuelle.",
  },
  {
    id: 74,
    domain: Domain.Donnees,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Que signifie figer les volets ?",
    options: ["Verrouiller le fichier", "Garder les titres visibles lors du défilement", "Empêcher la saisie", "Masquer le ruban"],
    correctAnswer: 1,
    explanation: "Indispensable pour les grands tableaux où on perd sinon la vue des en-têtes.",
    trap: "Confondre avec 'Protéger la feuille'.",
    tip: "Toujours figer les titres.",
  },
  {
    id: 75,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment obtenir le nom du jour de la semaine (ex: 'Lundi') à partir d'une date en A1 ?",
    correctAnswer: "=TEXTE(A1;\"jjjj\")",
    explanation: "La fonction TEXTE avec le format 'jjjj' convertit une date en nom de jour.",
    trap: "La fonction JOUR() ne donne que le chiffre (1 à 31).",
    tip: "TEXTE pour formater.",
  },
  {
    id: 76,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Raccourci clavier pour créer un nouveau classeur vierge.",
    correctAnswer: "Ctrl+N",
    explanation: "N pour Nouveau / New.",
    trap: "Ctrl+O (Open) qui ouvre un fichier existant.",
    tip: "Ctrl+N.",
  },
  {
    id: 77,
    domain: Domain.Calculs,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Formule pour diviser la somme de A1 et A2 par 2.",
    correctAnswer: "=(A1+A2)/2",
    explanation: "Les parenthèses sont obligatoires pour que l'addition se fasse avant la division.",
    trap: "A1+A2/2 (la division se ferait en premier : priorité des opérateurs).",
    tip: "Parenthèses = Priorité.",
  },
  {
    id: 78,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Comment copier la mise en forme de plusieurs plages non adjacentes en une fois ?",
    options: ["Un clic sur le pinceau", "Double-clic sur le pinceau", "Clic droit > Pinceau", "On ne peut pas"],
    correctAnswer: 1,
    explanation: "Le double-clic verrouille l'outil pinceau jusqu'à ce qu'on appuie sur Echap.",
    trap: "Le clic simple ne permet qu'une seule application.",
    tip: "Double-cliquez le pinceau !",
  },
  {
    id: 79,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Où se trouve l'option pour convertir une colonne de texte (ex: nom et prénom) en deux colonnes séparées ?",
    correctAnswer: "Données > Convertir",
    explanation: "L'assistant Conversion permet de séparer par un délimiteur (espace, virgule...).",
    trap: "Chercher dans Insertion.",
    tip: "Données > Convertir.",
  },
  {
    id: 80,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Écrire une formule qui renvoie le prix en A1 si A1 est supérieur à 100, sinon renvoie 0.",
    correctAnswer: "=SI(A1>100;A1;0)",
    explanation: "Utilisation classique de la fonction SI.",
    trap: "Mettre des guillemets autour de A1 ou 0 (ce sont des nombres, pas du texte).",
    tip: "SI(Quoi; SiVrai; SiFaux).",
  },
  {
    id: 81,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Quelle fonctionnalité permet de collaborer en temps réel sur un fichier Excel ?",
    options: ["Envoyer par mail", "Co-édition (via OneDrive/SharePoint)", "Le figer", "Le transformer en PDF"],
    correctAnswer: 1,
    explanation: "Le cloud Microsoft permet à plusieurs personnes d'écrire en même temps.",
    trap: "Le partage de fichier classique fige souvent le fichier pour les autres.",
    tip: "Besoin du cloud pour le temps réel.",
  },
  {
    id: 82,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Quelle fonction renvoie le nombre de caractères d'une chaîne en A1 ?",
    correctAnswer: "=NBCAR(A1)",
    explanation: "NBCAR compte les lettres, chiffres, symboles et espaces.",
    trap: "Confondre avec NB qui compte des cellules.",
    tip: "NBCAR = Nb Caractères.",
  },
  {
    id: 83,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Dans quel outil d'Excel crée-t-on des règles du type 'Si la cellule contient 'Urgent', mettre le fond en rouge' ?",
    options: ["Format de cellule", "Mise en forme conditionnelle", "Validation des données", "Styles de cellule"],
    correctAnswer: 1,
    explanation: "C'est le rôle exact de la Mise en forme conditionnelle.",
    trap: "La 'Validation des données' contrôle la saisie, pas l'apparence.",
    tip: "Conditionnelle = Selon le contenu.",
  },
  {
    id: 84,
    domain: Domain.Donnees,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quel bouton cliquer pour afficher seulement les lignes d'un tableau correspondant à un critère spécifique ?",
    options: ["Trier", "Filtre", "Grouper", "Format"],
    correctAnswer: 1,
    explanation: "Le filtre masque les données ne répondant pas au critère.",
    trap: "Le tri change l'ordre mais ne masque rien.",
    tip: "Filtre = Entonnoir.",
  },
  {
    id: 85,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Formule pour insérer l'heure actuelle de façon non dynamique (raccourci).",
    correctAnswer: "Ctrl+:",
    explanation: "Ctrl+: (deux points) insert l'heure fixe. (Note: en formule dynamique c'est MAINTENANT())",
    trap: "Confondre avec Ctrl+; (point-virgule) qui insère la date.",
    tip: "Raccourcis statiques pratiques.",
  },
  {
    id: 86,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Comment s'appelle l'intersection d'une ligne et d'une colonne ?",
    options: ["Un bloc", "Une cellule", "Un champ", "Une valeur"],
    correctAnswer: 1,
    explanation: "Chaque case d'Excel est une cellule identifiée par son adresse (ex: B5).",
    trap: "Un champ est un terme de base de données.",
    tip: "Une cellule.",
  },
  {
    id: 87,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Formule pour multiplier la somme de A1:A5 par la valeur en B1.",
    correctAnswer: "=SOMME(A1:A5)*B1",
    explanation: "On fait la somme d'abord, puis le produit.",
    trap: "SOMME(A1:A5*B1) est incorrect syntaxiquement.",
    tip: "Fonction * Valeur.",
  },
  {
    id: 88,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Où changer l'orientation du texte (ex : texte vertical) ?",
    options: ["Format de cellule > Alignement", "Onglet Insertion", "Onglet Révision", "N'existe pas"],
    correctAnswer: 0,
    explanation: "L'onglet Alignement permet de faire pivoter le texte de -90 à 90 degrés.",
    trap: "Chercher dans 'Police'.",
    tip: "Alignement = Position et angle.",
  },
  {
    id: 89,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment nommer une plage de cellules (ex: appeler A1:A10 'Ventes') ?",
    correctAnswer: "Zone de nom (en haut à gauche) ou Gestionnaire de noms",
    explanation: "Nommer une plage rend les formules plus lisibles (ex: =SOMME(Ventes)).",
    trap: "Il ne faut pas d'espaces dans un nom de plage.",
    tip: "Zone de nom = Rapide.",
  },
  {
    id: 90,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Formule pour compter le nombre de cellules vides dans la plage B1:B20.",
    correctAnswer: "=NB.VIDE(B1:B20)",
    explanation: "La fonction NB.VIDE compte uniquement les cases sans contenu.",
    trap: "Confondre avec NBVAL qui compte les cases non vides.",
    tip: "NB.VIDE.",
  },
  {
    id: 91,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Que signifie le mode 'Aperçu des sauts de page' ?",
    options: ["Voir le fichier en PDF", "Visualiser et ajuster ce qui sera sur chaque page à l'impression", "Masquer le ruban", "Accélérer l'affichage"],
    correctAnswer: 1,
    explanation: "Pratique pour éviter qu'une colonne ne soit coupée en deux à l'impression.",
    trap: "Il ne change pas le contenu, juste la répartition.",
    tip: "Onglet Affichage.",
  },
  {
    id: 92,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Extraire le premier mot de A1 (texte avant le premier espace).",
    correctAnswer: "=GAUCHE(A1;TROUVE(\" \";A1)-1)",
    explanation: "On cherche la position de l'espace et on prend tout ce qui est avant.",
    trap: "Oublier le -1 (on prendrait l'espace avec).",
    tip: "Formule complexe mais courante !",
  },
  {
    id: 93,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Facile,
    type: QuestionType.QCM,
    text: "Quel bouton permet d'effacer uniquement la couleur et la police d'une cellule sans supprimer le texte ?",
    options: ["Supprimer", "Effacer le contenu", "Effacer les formats", "Annuler"],
    correctAnswer: 2,
    explanation: "Le bouton 'Effacer' (gomme rose) a une option 'Effacer les formats'.",
    trap: "La touche 'Suppr' du clavier n'efface que le texte.",
    tip: "Gomme rose > Formats.",
  },
  {
    id: 94,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Comment actualiser un Tableau Croisé Dynamique après avoir modifié les données sources ?",
    correctAnswer: "Clic droit sur le TCD > Actualiser",
    explanation: "Contrairement aux formules, les TCD ne se mettent pas à jour en temps réel.",
    trap: "Penser que c'est automatique.",
    tip: "Ne jamais oublier d'Actualiser.",
  },
  {
    id: 95,
    domain: Domain.Calculs,
    difficulty: Difficulty.Facile,
    type: QuestionType.Practical,
    text: "Formule pour calculer la racine carrée de 25.",
    correctAnswer: "=RACINE(25)",
    explanation: "La fonction RACINE calcule la racine carrée d'un nombre positif.",
    trap: "Essayer de diviser par 2.",
    tip: "RACINE().",
  },
  {
    id: 96,
    domain: Domain.EnvMethod,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "À quoi sert la fonction 'Inspecter le document' ?",
    options: ["Chercher des virus", "Vérifier la présence de données cachées ou personnelles avant partage", "Réparer les formules", "Traduire le fichier"],
    correctAnswer: 1,
    explanation: "Elle permet de supprimer les commentaires, les propriétés de l'auteur, etc.",
    trap: "Elle ne vérifie pas la logique des calculs.",
    tip: "Fichier > Informations > Rechercher des problèmes.",
  },
  {
    id: 97,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Formule pour obtenir le dernier jour du mois de la date en A1.",
    correctAnswer: "=FIN.MOIS(A1;0)",
    explanation: "FIN.MOIS avec l'argument '0' renvoie le dernier jour du mois en cours.",
    trap: "Essayer de le deviner avec JOUR() (trop complexe).",
    tip: "FIN.MOIS.",
  },
  {
    id: 98,
    domain: Domain.MiseEnForme,
    difficulty: Difficulty.Moyen,
    type: QuestionType.QCM,
    text: "Que permet l'option 'Reproduire la mise en forme' ?",
    options: ["Copier le texte", "Copier le style (couleur, police, bordures)", "Cloner tout le fichier", "Imprimer deux fois"],
    correctAnswer: 1,
    explanation: "C'est l'outil pinceau.",
    trap: "Il ne copie jamais la valeur/le texte.",
    tip: "Pinceau = Look.",
  },
  {
    id: 99,
    domain: Domain.Donnees,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Quel raccourci permet d'insérer un nouveau graphique à partir des données sélectionnées ?",
    correctAnswer: "Alt+F1 (ou F11 pour une feuille séparée)",
    explanation: "Alt+F1 insère un graphique objet dans la feuille active.",
    trap: "Ctrl+G qui sert à 'Atteindre'.",
    tip: "Graphique express : Alt+F1.",
  },
  {
    id: 100,
    domain: Domain.Calculs,
    difficulty: Difficulty.Moyen,
    type: QuestionType.Practical,
    text: "Bravo ! Dernière question : Formule pour arrondir A1 à la dizaine supérieure (ex : 123 -> 130).",
    correctAnswer: "=ARRONDI.SUP(A1;-1)",
    explanation: "Un nombre de décimales négatif (-1) arrondit à gauche de la virgule (dizaines).",
    trap: "Utiliser 1 au lieu de -1.",
    tip: "Négatif = Gauche de la virgule.",
  }
];

export const getQuestionsByLevel = (level: TosaLevel, count: number) => {
  let ratioM = 0.2;
  if (level === TosaLevel.Operationnel) ratioM = 0.4;
  if (level === TosaLevel.Avance) ratioM = 0.55;
  if (level === TosaLevel.Expert) ratioM = 0.7;

  const countM = Math.round(count * ratioM);
  const countF = count - countM;

  const facile = QUESTIONS.filter(q => q.difficulty === Difficulty.Facile);
  const moyen = QUESTIONS.filter(q => q.difficulty === Difficulty.Moyen);

  const shuffledF = [...facile].sort(() => 0.5 - Math.random());
  const shuffledM = [...moyen].sort(() => 0.5 - Math.random());

  const result = [...shuffledF.slice(0, countF), ...shuffledM.slice(0, countM)];
  return result.sort((a, b) => {
    if (a.difficulty === b.difficulty) return 0.5 - Math.random();
    return a.difficulty === Difficulty.Facile ? -1 : 1;
  });
};

